# hostname (and path) to the root eg. http://spf13.com/
baseurl = "http://ppone.github.io"

# Site title
title = "Thoughtful Insights"

# Copyright
copyright = "(c) 2015 Parag Patel"

# Language
languageCode = "en-EN"

# Metadata format
# "yaml", "toml", "json"
metaDataFormat = "toml"

# Theme to use (located in /themes/THEMENAME/)
theme = "hyde-y"

# Pagination
paginate = 10
paginatePath = "page"

# Enable Disqus integration
disqusShortname = "disqus_vE389Z5pkE"


[permalinks]
    post = "/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"

[author]
    name = "Parag Patel"
    email = "parag@invoiced.com"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # You can use markdown here.
      brand = "Parag Patel"
      topline = "Co-founder of <a href=\"https://invoiced.com\">Invoiced</a>"
      ootline = "code with <i class='fa fa-heart'></i>"

    # Sidebar position
      # false, true, "left", "right"
     sidebar = "left"

    # Text for the top menu link, which goes the root URL for the site.
        # Default (if omitted) is "Home".
      home = "Home"

    # Select a syntax highight.
        # Check the static/css/highlight directory for options.
	    highlight = "default"

    # Google Analytics.
        googleAnalytics = "Your Google Analytics tracking code"

    # Sidebar social links.
        github = "ppone" # Your Github profile ID
	linkedin = "paragpatelone" # Your LinkedIn profile ID (from public URL)
        twitter = "paragpatelone" # Your Twitter profile ID
	

[blackfriday]
    angledQuotes = true
        fractions = false
	    hrefTargetBlank = false
	        latexDashes = true
		    plainIdAnchors = true
		        extensions = []
			    extensionmask = []

